name: Release

on:
  release:
    types: [ created ]

jobs:
  cargo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: cargo build --release
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}